### ISSUE TITLE
Get "attempting to disconnect view that has not been connected with the given animated node" Error

### ISSUE THREAD

**Issue by aminsaedi** [miblanchard/react-native-slider#298] opened 2021-06-27 08:33 UTC
Hi.
i got this error when i change the value of slider
`attempting to disconnect view that has not been connected with the given animated node`

**Comment by miblanchard** [comment] 2021-07-25 15:59
@aminsaedi Can you provide any more information or a reproducible example of how you are using the library?

**Comment by miblanchard** [comment] 2021-08-21 15:24
@aminsaedi I'm gonna close this since you haven't provided a reproducible example and I can't reproduce on my own.

**Closed as completed by miblanchard** 2021-08-21 15:24 UTC
