### ISSUE TITLE
minimumTrackStyle and maximumTrackStyle

### ISSUE THREAD

**Issue by luisfuertes** [miblanchard/react-native-slider#366] opened 2022-09-20 15:30 UTC
Thanks for your component is great.

I just miss being able to change the style of each track separately. For example maxiumTrack height and miniumTrack height separately.

If you can add minimumTrackStyle and maximumTrackStyle it would be great

Thanks

**Comment by matpiwowarski** [comment] 2022-10-24 22:49
That would be very useful! 

I found a workaround for height, but it would be useful to have something done by the authors of the library.

https://stackoverflow.com/questions/74187491/different-height-of-maximum-and-minimum-track-using-react-native-slider

**Comment by g7i** [comment] 2022-10-25 10:07
Duplicate of #354

**Comment by miblanchard** [comment] 2022-11-15 06:12
Closed by #355

**Closed as completed by miblanchard** 2022-11-15 06:12 UTC
