### ISSUE TITLE
Unable to upgrade react-native and react to latest version

### ISSUE THREAD

**Issue by AlenToma** [miblanchard/react-native-slider#221] opened 2021-03-25 01:15 UTC
Hi.

I am unable to upgrade my packages to the latest version when using this library.

Could you please have a look at this.

```

npm update 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: novelmanager@1.0.5
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@">=16.8.0" from @miblanchard/react-native-slider@1.5.0
npm ERR!   node_modules/@miblanchard/react-native-slider
npm ERR!     @miblanchard/react-native-slider@"^1.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.64.0" from the root project
npm ERR!   peer react-native@">=0.59.0" from @miblanchard/react-native-slider@1.5.0
npm ERR!   node_modules/@miblanchard/react-native-slider
npm ERR!     @miblanchard/react-native-slider@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\alen\AppData\Local\npm-cache\eresolve-report.txt for a full report.

```

There is some conflict between the packages, even thought in your page it says that i should not have problem upgrading `react-native` and `react `

**Comment by miblanchard** [comment] 2021-06-06 19:01
@AlenToma - Are you still experiencing this issue?  The react and react native peer dependencies from this package should not install or stop you from installing other versions.

**Comment by AlenToma** [comment] 2021-06-07 03:29
I have not test it a second time.
Will do that soon, there is some packages I am waiting for before doing an upgrade to my react-native and react packages. 

But if you see the logs above it states that there is some dependency issue when upgrading. mining there is some code that may not exist in react or react-native  after the upgrade and that your library depends on it.

**Comment by maevic** [comment] 2021-06-09 19:34
Hi, I experience the same problem when trying to install this package. It seems npm has changed its behavior in version 7 and complains about unmet peer dependencies. You can find more information here: https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies

**Comment by miblanchard** [comment] 2021-08-21 13:45
@AlenToma since this appears to be an issue with npm, and not this library, I'm going to go ahead and close this issue. I have confirmed using new versions of react native when I use yarn as well.

**Closed as completed by miblanchard** 2021-08-21 13:45 UTC

**Comment by AlenToma** [comment] 2021-08-21 15:09
Yes, I do not have this problem anymore. sorry for the trouble
